"""
Django settings for ug_radio_django project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from os import getenv
from dotenv import load_dotenv
from pathlib import Path
from datetime import timedelta
load_dotenv()  # loads .env
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Overridable for local dev, where /srv/... won't exist. Defaults preserve prod behavior.
P_DIR = Path(getenv('JWT_PRIVATE_KEY_PATH', '/srv/mp3private.key'))
PUB_DIR = Path(getenv('JWT_PUBLIC_KEY_PATH', '/srv/mp3public.key'))
SIMPLE_JWT = {
    "ALGORITHM": "RS256",
    "SIGNING_KEY": P_DIR.read_text(),
    "VERIFYING_KEY": PUB_DIR.read_text(),
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret! In production,
# set DJANGO_SECRET_KEY as a real env var (e.g. in the systemd unit) — do NOT put
# it in the tracked .env file. This fallback is fine for local dev only.
SECRET_KEY = getenv('DJANGO_SECRET_KEY', 'django-insecure--00vaxs5nwhlgov1x09&-z7=c6e3h@2l6oit(*unsxix5=o+4-')

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True to preserve local dev behavior; production sets DJANGO_DEBUG=False.
DEBUG = getenv('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    '127.0.0.1',
    '72.61.75.183',
    'undergroundradio.us',
    'www.undergroundradio.us',
]


# Application definition
# ug_radio_django is the path where models.py which contains models
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp.apps.MyappConfig',
    'rest_framework',
    'django_extensions',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Frontend is a separate Next.js origin; auth uses Bearer tokens (not cookies),
# so no CORS_ALLOW_CREDENTIALS is needed.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Only views that opt in with throttle_scope = 'auth' are limited by this —
    # login/signup/password-reset, to blunt brute-force/credential-stuffing.
    # Everything else is unaffected.
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "auth": "10/min",
    },
}


ROOT_URLCONF = 'ug_radio_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ug_radio_django.wsgi.application'


# Database - Neon postgres in prod. Falls back to local SQLite when NEON_HOST
# isn't set (e.g. local dev without real Neon credentials); prod is unaffected
# since it always sets NEON_HOST.
if getenv('NEON_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': getenv('NEON_DB'),
            'USER': getenv('NEON_USER'),
            'PASSWORD': getenv('NEON_PASS'),
            'HOST': getenv('NEON_HOST'),
            'PORT': getenv('NEON_PORT', 5432),
            'OPTIONS': {
                'sslmode': 'require',
            },
            # Without this, Django opens a brand-new TCP+TLS+auth connection
            # to Neon (a remote host) on every single request and tears it
            # down at the end — every page nav (library/home/account each
            # hit the backend independently) was paying that full handshake
            # cost from scratch. Reuse connections for 60s instead; health
            # checks drop ones Neon closed server-side rather than erroring.
            'CONN_MAX_AGE': 60,
            'CONN_HEALTH_CHECKS': True,
        }
    }
else:
    # Deliberately not the tracked db.sqlite3 at the repo root — that file has
    # stale/inconsistent migration history baked in from an earlier run. This is
    # a fresh, gitignored dev-only database.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'dev.sqlite3',
        }
    }

# Email — Brevo SMTP relay. Falls back to printing to stdout when Brevo
# credentials aren't set (e.g. local dev), so email-sending code paths don't
# need a real provider to run locally.
EMAIL_HOST_USER = getenv('BREVO_SMTP_LOGIN')
EMAIL_HOST_PASSWORD = getenv('BREVO_SMTP_KEY')
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp-relay.brevo.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = getenv('DEFAULT_FROM_EMAIL', 'no-reply@undergroundradio.us')

AUTH_USER_MODEL = "myapp.User"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
