# Generated by Django 5.2.9 on 2026-07-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='coverArt',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='coverArt',
            field=models.CharField(blank=True),
        ),
    ]
