# Generated by Django 5.2.9 on 2026-08-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_library_coverart_alter_song_coverart'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.CharField(blank=True),
        ),
    ]
