# Generated by Django 5.2.9 on 2026-08-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_song_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
