# Generated by Django 5.2.9 on 2026-10-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_song_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
